# Generated by Django 4.2.7 on 2025-08-03 10:41

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_reply_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(max_length=4, unique=True, validators=[tickets.models.validate_employee_code], verbose_name='کد کارمندی'),
        ),
    ]
