# Generated by Django 4.2.7 on 2025-08-04 13:25

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_user_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(max_length=10, unique=True, validators=[tickets.models.validate_employee_code], verbose_name='کد کارمندی'),
        ),
    ]
