# Generated by Django 4.2.7 on 2025-08-04 15:24

from django.db import migrations, models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[tickets.validators.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[tickets.validators.validate_iranian_mobile_number], verbose_name='تلفن'),
        ),
    ]
