# Generated by Django 4.2.7 on 2025-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_user_national_id_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('senior', 'سرگروه')], default='employee', max_length=10, verbose_name='نقش در بخش'),
        ),
    ]
