# Generated by Django 4.2.7 on 2025-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_user_department_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(
                blank=True,
                choices=[
                    ('اداری', 'اداری'),
                    ('برنامه‌ریزی و کنترل پروژه', 'برنامه‌ریزی و کنترل پروژه'),
                    ('تدارکات', 'تدارکات'),
                    ('کنترل کیفیت', 'کنترل کیفیت'),
                    ('قراردادها', 'قراردادها'),
                    ('منابع انسانی', 'منابع انسانی'),
                    ('مناقصات', 'مناقصات'),
                    ('مهندسی و فنی', 'مهندسی و فنی'),
                    ('MTO', 'MTO'),
                    ('پروژه‌ها', 'پروژه‌ها'),
                    ('فیلتر فروش', 'فیلتر فروش'),
                ],
                max_length=100,
                null=True,
                verbose_name='بخش'
            ),
        ),
    ] 