# Generated by Django 4.2.7 on 2025-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('اداری', 'اداری'), ('برنامه\u200cریزی و کنترل پروژه', 'برنامه\u200cریزی و کنترل پروژه'), ('تدارکات', 'تدارکات'), ('کنترل کیفیت', 'کنترل کیفیت'), ('قراردادها', 'قراردادها'), ('منابع انسانی', 'منابع انسانی'), ('مناقصات', 'مناقصات'), ('مهندسی و فنی', 'مهندسی و فنی'), ('MTO', 'MTO'), ('پروژه\u200cها', 'پروژه\u200cها'), ('فیلتر فروش', 'فیلتر فروش'), ('پشتیبانی فنی', 'پشتیبانی فنی'), ('امنیت اطلاعات', 'امنیت اطلاعات'), ('توسعه نرم افزار', 'توسعه نرم افزار'), ('مدیریت پایگاه داده', 'مدیریت پایگاه داده'), ('مدیریت سیستم ها', 'مدیریت سیستم ها'), ('مدیریت شبکه', 'مدیریت شبکه'), ('سایر', 'سایر')], max_length=100, null=True, verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('technician', 'کارشناس فنی'), ('it_manager', 'مدیر فناوری اطلاعات')], default='employee', max_length=20, verbose_name='نقش'),
        ),
    ]
