# Generated by Django 4.2.7 on 2025-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_update_technician_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('hardware', 'سخت\u200cافزار'), ('software', 'نرم\u200cافزار'), ('network', 'شبکه'), ('access', 'Remote Access'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department_role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('senior', 'سرگروه'), ('manager', 'مدیر')], default='employee', max_length=10, verbose_name='نقش در بخش'),
        ),
    ]
