# Generated by Django 4.2.7 on 2025-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_set_it_manager_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال انجام'), ('waiting_for_user', 'در انتظار کاربر'), ('resolved', 'انجام شده'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت'),
        ),
    ]
