# Generated by Django 4.2.7 on 2025-08-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_access_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('hardware', 'سخت\u200cافزار'), ('software', 'نرم\u200cافزار'), ('network', 'شبکه'), ('access', 'دسترسی شبکه'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
    ]
