# Generated by Django 4.2.7 on 2025-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_notification_id_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(
                choices=[
                    ('tickets', 'تیکت‌ها'),
                    ('users', 'کاربران'),
                    ('system', 'سیستم'),
                    ('access', 'دسترسی')
                ],
                default='system',
                max_length=20,
                verbose_name='دسته‌بندی'
            ),
        ),
    ] 