# Generated by Django 4.2.7 on 2025-08-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_add_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(
                choices=[
                    ('tickets', 'تیکت‌ها'),
                    ('users', 'کاربران'),
                    ('system', 'سیستم'),
                    ('access', 'دسترسی شبکه'),
                    ('team_leader_access', 'درخواست‌های دسترسی شبکه')
                ],
                default='system',
                max_length=20,
                verbose_name='دسته‌بندی'
            ),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_actor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sent_notifications',
                to='tickets.user',
                verbose_name='کاربر ایجاد کننده'
            ),
        ),
    ] 