# Generated by Django 4.2.7 on 2025-08-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_rename_type_to_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_urgent', 'تیکت فوری'), ('ticket_created', 'تیکت جدید'), ('access_approved', 'تایید دسترسی شبکه'), ('access_pending_approval', 'در انتظار تایید دسترسی شبکه'), ('access_rejected', 'رد دسترسی شبکه'), ('user_created', 'ایجاد کاربر'), ('login', 'ورود'), ('status_done', 'انجام شد')], max_length=50, verbose_name='نوع'),
        ),
    ]
