# Generated by Django 4.2.7 on 2025-08-23 11:21

from django.db import migrations


def create_initial_departments(apps, schema_editor):
    """Create initial departments from hardcoded choices"""
    Department = apps.get_model('tickets', 'Department')
    
    # Define the old hardcoded department choices (excluding IT Department for security)
    EMPLOYEE_DEPARTMENTS = [
        ('HR Department', 'employee'),
        ('Finance Department', 'employee'),
        ('Marketing Department', 'employee'),
        ('Sales Department', 'employee'),
        ('Operations Department', 'employee'),
        ('Legal Department', 'employee'),
        ('Customer Service Department', 'employee'),
    ]
    
    TECHNICIAN_SECTIONS = [
        ('Network Section', 'technician'),
        ('Software Section', 'technician'),
        ('Hardware Section', 'technician'),
        ('Database Section', 'technician'),
        ('Security Section', 'technician'),
        ('Support Section', 'technician'),
    ]
    
    # Create employee departments
    for dept_name, dept_type in EMPLOYEE_DEPARTMENTS:
        Department.objects.get_or_create(
            name=dept_name,
            defaults={
                'department_type': dept_type,
                'description': f'{dept_name} - {dept_type} department',
                'is_active': True
            }
        )
    
    # Create technician departments
    for dept_name, dept_type in TECHNICIAN_SECTIONS:
        Department.objects.get_or_create(
            name=dept_name,
            defaults={
                'department_type': dept_type,
                'description': f'{dept_name} - {dept_type} section',
                'is_active': True
            }
        )


def reverse_create_initial_departments(apps, schema_editor):
    """Reverse migration - delete all departments"""
    Department = apps.get_model('tickets', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_add_department_model_step1'),
    ]

    operations = [
        migrations.RunPython(create_initial_departments, reverse_create_initial_departments),
    ]
