# Generated by Django 4.2.7 on 2025-08-23 11:27

from django.db import migrations, models
import django.db.models.deletion


def migrate_department_data(apps, schema_editor):
    """Migrate department string data to ForeignKey references"""
    User = apps.get_model('tickets', 'User')
    Department = apps.get_model('tickets', 'Department')
    
    # Get all departments
    departments = {dept.name: dept for dept in Department.objects.all()}
    
    # Update users with string department values
    for user in User.objects.all():
        if user.department and isinstance(user.department, str):
            if user.department in departments:
                user.department_new = departments[user.department]
                user.save()


def reverse_migrate_department_data(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to string"""
    User = apps.get_model('tickets', 'User')
    
    for user in User.objects.all():
        if user.department_new and hasattr(user.department_new, 'name'):
            user.department = user.department_new.name
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_create_initial_departments'),
    ]

    operations = [
        # Add new ForeignKey field
        migrations.AddField(
            model_name='user',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_new', to='tickets.department', verbose_name='بخش جدید'),
        ),
        
        # Migrate data
        migrations.RunPython(migrate_department_data, reverse_migrate_department_data),
        
        # Remove old field
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        
        # Rename new field to original name
        migrations.RenameField(
            model_name='user',
            old_name='department_new',
            new_name='department',
        ),
    ]
