# Generated by Django 4.2.7 on 2025-08-23 12:14

from django.db import migrations


def remove_it_department(apps, schema_editor):
    """Remove IT Department and update users who have it assigned"""
    User = apps.get_model('tickets', 'User')
    Department = apps.get_model('tickets', 'Department')
    
    # Find and remove IT Department
    try:
        it_department = Department.objects.get(name='IT Department')
        
        # Update all users who have IT Department assigned to have no department
        User.objects.filter(department=it_department).update(department=None)
        
        # Delete the IT Department
        it_department.delete()
        print("IT Department removed successfully")
        
    except Department.DoesNotExist:
        print("IT Department not found - already removed")


def reverse_remove_it_department(apps, schema_editor):
    """Reverse migration - recreate IT Department"""
    Department = apps.get_model('tickets', 'Department')
    
    # Recreate IT Department
    Department.objects.get_or_create(
        name='IT Department',
        defaults={
            'department_type': 'employee',
            'description': 'IT Department - employee department',
            'is_active': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_add_department_foreign_key_manual'),
    ]

    operations = [
        migrations.RunPython(remove_it_department, reverse_remove_it_department),
    ]
