# Generated by Django 4.2.7 on 2025-08-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_remove_it_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=255, verbose_name='هاست SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='پورت')),
                ('use_tls', models.BooleanField(default=True, verbose_name='استفاده از TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='استفاده از SSL')),
                ('username', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل فرستنده')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور ایمیل')),
                ('from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام نمایشی فرستنده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات ایمیل',
                'verbose_name_plural': 'تنظیمات ایمیل',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.department', verbose_name='بخش'),
        ),
    ]
