# Generated by Django 4.2.7 on 2025-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_emailconfig_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_private',
            field=models.BooleanField(default=False, help_text='این پاسخ فقط برای کارمند دریافت\u200cکننده قابل مشاهده است', verbose_name='پاسخ محرمانه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='access_approval_status',
            field=models.CharField(choices=[('not_required', 'بدون نیاز به تایید'), ('pending', 'در انتظار تایید سرپرست'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='not_required', max_length=20, verbose_name='وضعیت تایید دسترسی شبکه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department_role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('senior', 'سرپرست'), ('manager', 'مدیر')], default='employee', max_length=10, verbose_name='نقش در بخش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'کارمند'), ('technician', 'کارشناس فنی'), ('it_manager', 'مدیر IT')], default='employee', max_length=20, verbose_name='نقش'),
        ),
    ]
