# Generated by Django 4.2.7 on 2025-09-14 10:56

from django.db import migrations, models
import tickets.models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_update_senior_role_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(error_messages={'unique': 'بخشی با این نام قبلاً وجود دارد.'}, max_length=100, unique=True, verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(error_messages={'unique': 'کاربری با این کد کارمندی قبلاً وجود دارد.'}, max_length=10, unique=True, validators=[tickets.models.validate_employee_code], verbose_name='کد کارمندی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(error_messages={'unique': 'کاربری با این کد ملی قبلاً وجود دارد.'}, max_length=20, unique=True, validators=[tickets.validators.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
    ]
