# Generated by Django 4.2.7 on 2025-12-01 15:15

from django.db import migrations, models
import django.db.models.deletion
import tickets.models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_alter_department_name_alter_user_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='can_receive_tickets',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، این بخش می\u200cتواند تیکت\u200cها را مستقیماً از کاربران دریافت کند', verbose_name='می\u200cتواند تیکت دریافت کند'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='target_department',
            field=models.ForeignKey(blank=True, help_text='بخشی که تیکت برای آن ارسال شده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tickets', to='tickets.department', verbose_name='بخش هدف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(error_messages={'unique': 'کاربر با این کد کارمندی وجود دارد.'}, max_length=10, unique=True, validators=[tickets.models.validate_employee_code], verbose_name='کد کارمندی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(error_messages={'unique': 'کاربر با این کد ملی وجود دارد.'}, max_length=20, unique=True, validators=[tickets.validators.validate_iranian_national_id], verbose_name='کد ملی'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('branch_code', models.CharField(help_text='کد یکتا برای هر بخش', max_length=50, verbose_name='کد شعبه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tickets.department', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='شعبه این بخش (الزامی)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='tickets.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.branch', verbose_name='شعبه'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('department', 'branch_code'), name='unique_branch_code_per_department'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('department', 'branch_code')},
        ),
    ]
