# Generated by Django 4.2.7 on 2025-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_department_can_receive_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_code_per_department',
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(help_text='کد یکتا برای شعبه (باید در تمام سیستم یکتا باشد)', max_length=50, unique=True, verbose_name='کد شعبه'),
        ),
    ]
