# Generated by Django 4.2.7 on 2025-12-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_remove_branch_unique_branch_code_per_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'شعبه', 'verbose_name_plural': 'شعبه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='department',
        ),
    ]
