# Generated by Django 4.2.7 on 2025-12-06 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_branch_options_remove_branch_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام عنصر موجودی (مثال: کیس کامپیوتر)', max_length=200, verbose_name='نام')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره این عنصر', null=True, verbose_name='توضیحات')),
                ('element_type', models.CharField(help_text='نوع عنصر (مثال: کامپیوتر، مانیتور، ماوس، کیبورد)', max_length=100, verbose_name='نوع عنصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(help_text='کاربری که این عنصر به او اختصاص داده شده است', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_elements', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_elements', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('parent_element', models.ForeignKey(blank=True, help_text='اگر این عنصر زیرمجموعه عنصر دیگری است، آن را انتخاب کنید', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_elements', to='tickets.inventoryelement', verbose_name='عنصر والد')),
            ],
            options={
                'verbose_name': 'عنصر موجودی',
                'verbose_name_plural': 'عناصر موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElementSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='نام مشخصه (مثال: IP، MAC، شماره سریال)', max_length=100, verbose_name='کلید')),
                ('value', models.TextField(help_text='مقدار مشخصه', verbose_name='مقدار')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره این مشخصه', null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('element', models.ForeignKey(help_text='عنصر موجودی که این مشخصه به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='tickets.inventoryelement', verbose_name='عنصر')),
            ],
            options={
                'verbose_name': 'مشخصه عنصر',
                'verbose_name_plural': 'مشخصات عناصر',
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryelement',
            index=models.Index(fields=['assigned_to', 'is_active'], name='tickets_inv_assigne_21dbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryelement',
            index=models.Index(fields=['parent_element'], name='tickets_inv_parent__a76abd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elementspecification',
            unique_together={('element', 'key')},
        ),
    ]
