# Generated by Django 4.2.7 on 2025-12-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_inventoryelement_elementspecification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ticket_responder',
            field=models.ForeignKey(blank=True, help_text='کارمندی که می\u200cتواند به تیکت\u200cهای دریافتی این بخش پاسخ دهد و وضعیت آن\u200cها را تغییر دهد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_responder', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده تیکت'),
        ),
    ]
