# Generated by Django 4.2.7 on 2025-12-09 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_tickettask_taskreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='کاربری که سرپرست این بخش است (فقط یک سرپرست برای هر بخش)', limit_choices_to={'department_role': 'senior', 'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_as_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervised_departments',
            field=models.ManyToManyField(blank=True, help_text='بخش\u200cهایی که این کاربر سرپرست آن\u200cها است', related_name='supervisors', to='tickets.department', verbose_name='بخش\u200cهای تحت سرپرستی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.department', verbose_name='بخش اصلی'),
        ),
    ]
