# Generated by Django 4.2.7 on 2025-12-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_add_deadline_to_tickettask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='سال')),
                ('month', models.IntegerField(db_index=True, verbose_name='ماه')),
                ('day', models.IntegerField(db_index=True, verbose_name='روز')),
                ('solar_date', models.CharField(help_text='فرمت: YYYY/MM/DD', max_length=20, verbose_name='تاریخ شمسی')),
                ('gregorian_date', models.CharField(help_text='فرمت: YYYY-MM-DD', max_length=20, verbose_name='تاریخ میلادی')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='تعطیل رسمی')),
                ('events_json', models.JSONField(default=list, help_text='آرایه رویدادهای فارسی برای این روز', verbose_name='رویدادها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'روز تقویم',
                'verbose_name_plural': 'روزهای تقویم',
                'ordering': ['year', 'month', 'day'],
                'indexes': [models.Index(fields=['year', 'month'], name='tickets_cal_year_6b48f1_idx')],
                'unique_together': {('year', 'month', 'day')},
            },
        ),
    ]
