# Generated by Django 4.2.7 on 2025-12-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_ticketactivitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketactivitylog',
            new_name='tickets_tic_ticket__3a1c22_idx',
            old_name='tickets_tic_ticket__idx',
        ),
        migrations.RenameIndex(
            model_name='ticketactivitylog',
            new_name='tickets_tic_user_id_11e980_idx',
            old_name='tickets_tic_user_id_idx',
        ),
    ]
