# Generated by Django 4.2.7 on 2025-12-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_department_has_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_service_provider',
            field=models.BooleanField(default=False, help_text='در صورتی که این بخش می\u200cتواند تیکت\u200cهای پشتیبانی دریافت کند، این گزینه را فعال کنید', verbose_name='ارائه\u200cدهنده خدمات'),
        ),
        migrations.AddField(
            model_name='department',
            name='service_provider_since',
            field=models.DateTimeField(blank=True, help_text='تاریخ فعال\u200cسازی این بخش به عنوان ارائه\u200cدهنده خدمات', null=True, verbose_name='ارائه خدمات از تاریخ'),
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دسته\u200cبندی تیکت (مثال: سخت\u200cافزار، شبکه، درخواست دسترسی)', max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, help_text='توضیحات اختیاری برای این دسته\u200cبندی', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت غیرفعال بودن، این دسته\u200cبندی در فرم ایجاد تیکت نمایش داده نمی\u200cشود', verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, help_text='ترتیب نمایش دسته\u200cبندی در لیست (اعداد کمتر در ابتدا نمایش داده می\u200cشوند)', verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('department', models.ForeignKey(help_text='بخش ارائه\u200cدهنده خدمات مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='tickets.department', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تیکت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت',
                'ordering': ['department', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_category',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی تیکت بر اساس بخش مقصد (سیستم جدید)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketcategory', verbose_name='دسته\u200cبندی جدید'),
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['department', 'is_active'], name='tickets_tic_departm_82cb88_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketcategory',
            index=models.Index(fields=['department', 'sort_order'], name='tickets_tic_departm_8d9163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketcategory',
            unique_together={('department', 'name')},
        ),
    ]
