# Generated by Django 4.2.7 on 2026-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0045_add_notification_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='requires_supervisor_approval',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، تیکت\u200cهای این دسته\u200cبندی نیاز به تایید سرپرست بخش ایجادکننده دارند', verbose_name='نیاز به تایید سرپرست'),
        ),
    ]
