# Generated by Django 4.2.7 on 2026-02-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_add_requires_supervisor_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_deadline', models.DateTimeField(help_text='مهلت جدید مورد درخواست', verbose_name='مهلت درخواستی')),
                ('reason', models.TextField(help_text='توضیح دلیل درخواست تمدید مهلت', verbose_name='دلیل درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='نظر بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL, verbose_name='بررسی کننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='tickets.tickettask', verbose_name='تسک')),
            ],
            options={
                'verbose_name': 'درخواست تمدید مهلت',
                'verbose_name_plural': 'درخواست\u200cهای تمدید مهلت',
                'ordering': ['-created_at'],
            },
        ),
    ]
