# Generated by Django 4.2.7 on 2026-02-17 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_add_deadline_reminder_sent_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='نام محصول یا اقلام مورد نیاز (مثال: موس 1، لپ تاپ 1)', max_length=200, verbose_name='نام محصول/اقلام')),
                ('description', models.TextField(help_text='توضیحات کامل درخواست امانت', verbose_name='توضیحات درخواست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('review_notes', models.TextField(blank=True, help_text='یادداشت\u200cهای مدیر IT در مورد این درخواست', null=True, verbose_name='یادداشت بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('requester', models.ForeignKey(help_text='کاربری که درخواست امانت را ثبت کرده است', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='مدیر IT که این درخواست را بررسی کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='بررسی شده توسط')),
            ],
            options={
                'verbose_name': 'درخواست امانت',
                'verbose_name_plural': 'درخواست\u200cهای امانت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='tickets_loa_request_9fb74f_idx'), models.Index(fields=['status'], name='tickets_loa_status_f6e501_idx')],
            },
        ),
    ]
