# Generated by Django 4.2.7 on 2026-02-17 11:41

from django.db import migrations, models
import django.utils.timezone
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_loanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_end_date',
            field=models.DateTimeField(default=tickets.models.get_default_loan_end_date, help_text='تاریخ و زمان تحویل دادن محصول', verbose_name='تاریخ تحویل دادن'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='تاریخ و زمان تحویل گرفتن محصول', verbose_name='تاریخ تحویل گرفتن'),
        ),
    ]
