# Generated by Django 4.2.7 on 2026-02-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_loanrequest_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_end_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ و زمان تحویل دادن محصول (توسط مدیر IT تعیین می\u200cشود)', null=True, verbose_name='تاریخ تحویل دادن'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_start_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ و زمان تحویل گرفتن محصول (توسط مدیر IT تعیین می\u200cشود)', null=True, verbose_name='تاریخ تحویل گرفتن'),
        ),
    ]
