# Generated by Django 4.2.7 on 2026-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_alter_loanrequest_loan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='has_technical_issue',
            field=models.BooleanField(default=False, help_text='آیا اقلام مشکل فنی یا جزئی دارد؟', verbose_name='دارای مشکل فنی/جزئی'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='technical_issue_description',
            field=models.TextField(blank=True, help_text='توضیحات مشکل فنی یا جزئی اقلام', null=True, verbose_name='توضیحات مشکل فنی/جزئی'),
        ),
    ]
