# Generated by Django 4.2.7 on 2026-02-18 10:04

from django.db import migrations, models


def reset_viewed_at_for_reviewed_loans(apps, schema_editor):
    """Reset viewed_at برای درخواست‌های تایید یا رد شده تا badge نمایش داده شود"""
    LoanRequest = apps.get_model('tickets', 'LoanRequest')
    # برای درخواست‌های تایید یا رد شده، viewed_at را null می‌کنیم
    LoanRequest.objects.filter(
        status__in=['approved', 'rejected']
    ).update(viewed_at=None)


def reverse_reset_viewed_at(apps, schema_editor):
    """Reverse migration - کاری انجام نمی‌دهیم"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_loanrequest_has_technical_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که کاربر درخواست را مشاهده کرده است', null=True, verbose_name='تاریخ مشاهده'),
        ),
        migrations.RunPython(reset_viewed_at_for_reviewed_loans, reverse_reset_viewed_at),
    ]
