# Generated by Django 4.2.7 on 2026-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0053_loanrequest_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='can_receive_tickets',
            field=models.BooleanField(blank=True, default=False, help_text='اگر فعال باشد، این بخش می\u200cتواند تیکت\u200cها را مستقیماً از کاربران دریافت کند', null=True, verbose_name='می\u200cتواند تیکت دریافت کند'),
        ),
        migrations.AlterField(
            model_name='department',
            name='has_warehouse',
            field=models.BooleanField(blank=True, default=False, help_text='اگر فعال باشد، سرپرست این بخش می\u200cتواند به ماژول انبار دسترسی داشته باشد', null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_service_provider',
            field=models.BooleanField(blank=True, default=False, help_text='در صورتی که این بخش می\u200cتواند تیکت\u200cهای پشتیبانی دریافت کند، این گزینه را فعال کنید', null=True, verbose_name='ارائه\u200cدهنده خدمات'),
        ),
    ]
