# Generated by Django 4.2.7 on 2026-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0054_department_nullable_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_inventory',
            field=models.BooleanField(blank=True, default=False, help_text='اگر فعال باشد، این بخش از ماژول Inventory استفاده می\u200cکند (مخصوص بخش\u200cهای IT)', null=True, verbose_name='Inventory'),
        ),
    ]
