# Generated by Django 4.2.7 on 2025-12-22 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0043_department_has_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام انبار این بخش', max_length=200, verbose_name='نام انبار')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dwms_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dwms_warehouse', to='tickets.department', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'انبار بخش',
                'verbose_name_plural': 'انبارهای بخش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('unit', models.CharField(default='عدد', help_text='مثال: عدد، متر، بسته', max_length=50, verbose_name='واحد')),
                ('sku', models.CharField(blank=True, help_text='کد داخلی کالا', max_length=100, null=True, verbose_name='کد کالا')),
                ('is_serialized', models.BooleanField(default=False, help_text='اگر فعال باشد، هر واحد به صورت جداگانه ردیابی می\u200cشود', verbose_name='سریال\u200cدار')),
                ('min_stock_threshold', models.DecimalField(decimal_places=2, default=0, help_text='هشدار کمبود موجودی در این مقدار فعال می\u200cشود', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل موجودی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محل')),
                ('code', models.CharField(blank=True, help_text='کد کوتاه برای شناسایی محل', max_length=50, null=True, verbose_name='کد محل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'محل نگهداری',
                'verbose_name_plural': 'محل\u200cهای نگهداری',
                'ordering': ['name'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(blank=True, help_text='کد بچ خرید یا شماره فاکتور', max_length=100, null=True, verbose_name='کد بچ')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='dwms.item', verbose_name='کالا')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='dwms.storagelocation', verbose_name='محل نگهداری')),
            ],
            options={
                'verbose_name': 'بچ موجودی',
                'verbose_name_plural': 'بچ\u200cهای موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='موجودی فعلی')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حد آستانه')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('ACKNOWLEDGED', 'تأیید شده'), ('RESOLVED', 'حل شده')], default='OPEN', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل شدن')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='dwms.item', verbose_name='کالا')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'هشدار کمبود موجودی',
                'verbose_name_plural': 'هشدارهای کمبود موجودی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ امانت')),
                ('due_date', models.DateField(verbose_name='تاریخ موعد بازگشت')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازگشت')),
                ('status', models.CharField(choices=[('OUT', 'امانت داده شده'), ('RETURNED', 'بازگردانده شده'), ('OVERDUE', 'تأخیر در بازگشت')], default='OUT', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lend_records', to='dwms.stockbatch', verbose_name='بچ')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_items', to=settings.AUTH_USER_MODEL, verbose_name='امانت\u200cگیرنده')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_lends', to=settings.AUTH_USER_MODEL, verbose_name='امانت داده شده توسط')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_records', to='dwms.item', verbose_name='کالا')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL, verbose_name='دریافت شده توسط')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_records', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'سابقه امانت',
                'verbose_name_plural': 'سوابق امانت',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ItemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('QR', 'QR Code'), ('BARCODE128', 'Barcode 128'), ('EAN13', 'EAN-13')], default='QR', max_length=20, verbose_name='نوع کد')),
                ('code_value', models.CharField(help_text='کد یکتا برای اسکن', max_length=200, unique=True, verbose_name='مقدار کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='dwms.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'کد کالا',
                'verbose_name_plural': 'کدهای کالا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='dwms.itemcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dwms.departmentwarehouse', verbose_name='انبار'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'ورود'), ('OUT', 'خروج'), ('ADJUSTMENT', 'اصلاح')], max_length=20, verbose_name='نوع حرکت')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ حرکت')),
                ('reason', models.CharField(choices=[('INITIAL_STOCK', 'موجودی اولیه'), ('PURCHASE', 'خرید'), ('LEND', 'امانت'), ('RETURN', 'بازگشت از امانت'), ('CONSUMPTION', 'مصرف'), ('TRANSFER', 'انتقال'), ('CORRECTION', 'اصلاح'), ('OTHER', 'سایر')], default='OTHER', max_length=50, verbose_name='دلیل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dwms.stockbatch', verbose_name='بچ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dwms.item', verbose_name='کالا')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dwms.storagelocation', verbose_name='محل نگهداری')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dwms_movements', to=settings.AUTH_USER_MODEL, verbose_name='انجام شده توسط')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'حرکت موجودی',
                'verbose_name_plural': 'حرکت\u200cهای موجودی',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'movement_date'], name='dwms_stockm_warehou_6b4a5d_idx'), models.Index(fields=['item', 'movement_date'], name='dwms_stockm_item_id_94d711_idx'), models.Index(fields=['performed_by', 'movement_date'], name='dwms_stockm_perform_018a76_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['item', 'location'], name='dwms_stockb_item_id_21e0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lowstockalert',
            index=models.Index(fields=['warehouse', 'status'], name='dwms_lowsto_warehou_d65536_idx'),
        ),
        migrations.AddIndex(
            model_name='lendrecord',
            index=models.Index(fields=['warehouse', 'status'], name='dwms_lendre_warehou_cfcc16_idx'),
        ),
        migrations.AddIndex(
            model_name='lendrecord',
            index=models.Index(fields=['borrower', 'status'], name='dwms_lendre_borrowe_c2e3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lendrecord',
            index=models.Index(fields=['due_date'], name='dwms_lendre_due_dat_fa8347_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcode',
            index=models.Index(fields=['code_value'], name='dwms_itemco_code_va_196e02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcategory',
            unique_together={('warehouse', 'name')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['warehouse', 'is_active'], name='dwms_item_warehou_c42801_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='dwms_item_categor_2878b4_idx'),
        ),
    ]
