# Generated by Django 4.2.7 on 2025-12-23 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dwms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'فقط مشاهده'), ('write', 'ویرایش و تغییر')], default='read', max_length=10, verbose_name='سطح دسترسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعطا')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('notes', models.TextField(blank=True, help_text='یادداشت اختیاری در مورد این دسترسی', null=True, verbose_name='یادداشت')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_warehouse_accesses', to=settings.AUTH_USER_MODEL, verbose_name='اعطا شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_accesses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='dwms.departmentwarehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'دسترسی انبار',
                'verbose_name_plural': 'دسترسی\u200cهای انبار',
                'indexes': [models.Index(fields=['warehouse', 'is_active'], name='dwms_wareho_warehou_0da36a_idx'), models.Index(fields=['user', 'is_active'], name='dwms_wareho_user_id_7db163_idx')],
                'unique_together': {('user', 'warehouse')},
            },
        ),
    ]
